// ---------------------------------------------------------------------------
// 05 · Base de conhecimento: Normas Regulamentadoras, glossário, orientações
//      Resumos para orientação rápida — sempre confira o texto vigente em
//      gov.br/trabalho-e-emprego (as NRs são atualizadas com frequência).
// ---------------------------------------------------------------------------
const NR_SOURCE = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes';

const NRS = {
  1: {
    titulo: 'Disposições Gerais e Gerenciamento de Riscos Ocupacionais',
    resumo: 'Define as regras comuns a todas as NRs e o GRO (Gerenciamento de Riscos Ocupacionais), materializado no PGR (Programa de Gerenciamento de Riscos).',
    pontos: [
      'O GRO deve ser implementado por estabelecimento; o PGR contém, no mínimo, o inventário de riscos e o plano de ação.',
      'Avaliação de riscos por gravidade × probabilidade, incluindo fatores ergonômicos e, desde a Portaria MTE nº 1.419/2024, os fatores de riscos psicossociais relacionados ao trabalho.',
      'Hierarquia de controles: eliminação, substituição/minimização, proteção coletiva, medidas administrativas e, por último, EPI.',
      'O trabalhador deve ser informado sobre riscos e medidas de prevenção (ordens de serviço, procedimentos, treinamentos).',
      'Direito de recusa: o trabalhador pode interromper a atividade diante de risco grave e iminente, comunicando imediatamente o superior.',
      'Treinamentos: inicial, periódico e eventual; permite EAD/semipresencial conforme o Anexo II e aproveitamento de treinamentos em certas condições.',
    ],
    documentos: ['PGR (inventário de riscos + plano de ação)', 'Ordens de serviço/procedimentos', 'Registros de capacitação'],
    palavras: 'gro pgr gerenciamento inventario plano de acao risco psicossocial direito de recusa ordem de servico treinamento ead',
  },
  3: { titulo: 'Embargo e Interdição', resumo: 'Trata do embargo de obra e da interdição de atividade, máquina ou setor quando a fiscalização constata grave e iminente risco ao trabalhador.', pontos: ['Medidas de urgência aplicadas pela Auditoria-Fiscal do Trabalho.', 'Durante a paralisação, os salários são devidos normalmente.'], palavras: 'embargo interdicao risco grave iminente fiscalizacao' },
  4: {
    titulo: 'Serviços Especializados em Segurança e Medicina do Trabalho (SESMT)',
    resumo: 'Define quando a empresa precisa manter SESMT e com quais profissionais, conforme o grau de risco da atividade (CNAE) e o número de empregados.',
    pontos: [
      'Dimensionamento pelo grau de risco (Anexo I) e pelo nº de empregados do estabelecimento (Anexo II).',
      'Profissionais: engenheiro de segurança, médico do trabalho, técnico de segurança, enfermeiro do trabalho e técnico/auxiliar de enfermagem do trabalho.',
      'Permite SESMT compartilhado/individual conforme regras da norma.',
    ],
    palavras: 'sesmt tecnico de seguranca engenheiro medico do trabalho dimensionamento grau de risco cnae',
  },
  5: {
    titulo: 'Comissão Interna de Prevenção de Acidentes e de Assédio (CIPA)',
    resumo: 'Regula a CIPA, comissão formada por representantes do empregador e dos empregados para prevenir acidentes, doenças e assédio no trabalho.',
    pontos: [
      'Dimensionamento conforme o Quadro I (grau de risco × nº de empregados); abaixo do quadro, a empresa nomeia um representante.',
      'Mandato de 1 ano, permitida uma reeleição; estabilidade do eleito desde o registro da candidatura até 1 ano após o mandato.',
      'Treinamento dos membros: 8h (grau de risco 1), 12h (GR 2), 16h (GR 3) e 20h (GR 4).',
      'Reuniões ordinárias mensais, conforme calendário; participação na identificação de riscos e no acompanhamento do PGR.',
      'Com a Lei 14.457/2022, passou a atuar também na prevenção e no combate ao assédio sexual e outras formas de violência.',
    ],
    documentos: ['Atas de eleição, posse e reuniões', 'Calendário de reuniões', 'Certificados de treinamento dos cipeiros'],
    palavras: 'cipa cipeiro assedio eleicao mandato sipat reuniao comissao',
  },
  6: {
    titulo: 'Equipamentos de Proteção Individual (EPI)',
    resumo: 'Estabelece regras para seleção, fornecimento, uso, guarda e registro de EPIs, que só podem ser usados com CA (Certificado de Aprovação) válido.',
    pontos: [
      'Empregador: fornecer gratuitamente o EPI adequado ao risco, exigir o uso, orientar e treinar, substituir quando danificado ou extraviado, higienizar/manter e registrar o fornecimento.',
      'Empregado: usar o EPI apenas para a finalidade, responsabilizar-se pela guarda e conservação e comunicar qualquer alteração que o torne impróprio.',
      'Todo EPI precisa de CA válido emitido pelo órgão nacional competente.',
      'O registro de entrega pode ser feito em livros, fichas ou sistema eletrônico (inclusive biometria).',
      'A recusa injustificada ao uso do EPI fornecido constitui ato faltoso do empregado (CLT, art. 158, parágrafo único).',
    ],
    documentos: ['Ficha de entrega de EPI', 'Registro de treinamentos de uso', 'Seleção técnica do EPI no PGR'],
    palavras: 'epi ca certificado de aprovacao ficha de epi entrega uso obrigatorio protetor auricular luva capacete oculos mascara',
  },
  7: {
    titulo: 'Programa de Controle Médico de Saúde Ocupacional (PCMSO)',
    resumo: 'Obriga o PCMSO, que planeja e registra os exames médicos ocupacionais de acordo com os riscos do PGR.',
    pontos: [
      'Exames: admissional, periódico, de retorno ao trabalho, de mudança de risco ocupacional e demissional — cada um gera um ASO.',
      'Retorno ao trabalho: antes de reassumir, quando afastado por 30 dias ou mais por doença ou acidente (ocupacional ou não).',
      'Periodicidade definida no PCMSO conforme os riscos (em geral anual para expostos a riscos e a cada 2 anos para os demais).',
      'Relatório analítico anual do PCMSO.',
    ],
    documentos: ['PCMSO', 'ASOs', 'Relatório analítico'],
    palavras: 'pcmso aso exame admissional periodico demissional retorno medico do trabalho audiometria',
  },
  8: { titulo: 'Edificações', resumo: 'Requisitos mínimos de segurança nas edificações: pisos, escadas, rampas, aberturas, proteção contra quedas e intempéries.', pontos: ['Pisos sem saliências ou depressões que prejudiquem a circulação.', 'Aberturas nos pisos e paredes protegidas contra quedas.', 'Escadas e rampas resistentes, com corrimão e piso antiderrapante quando necessário.'], palavras: 'edificacao piso escada rampa abertura guarda-corpo' },
  9: {
    titulo: 'Avaliação e Controle das Exposições Ocupacionais a Agentes Físicos, Químicos e Biológicos',
    resumo: 'Complementa o GRO com requisitos para identificar, avaliar e controlar exposições a agentes físicos, químicos e biológicos.',
    pontos: [
      'Avaliações quantitativas quando necessárias para dimensionar a exposição e verificar a eficácia das medidas.',
      'Nível de ação: metade do limite de exposição (para ruído, dose de 0,5 — equivalente a 80 dB(A) em 8h), a partir do qual se iniciam ações preventivas.',
      'Anexos tratam de vibração, calor e agentes químicos específicos.',
    ],
    palavras: 'agente fisico quimico biologico exposicao nivel de acao dosimetria avaliacao quantitativa vibracao calor',
  },
  10: {
    titulo: 'Segurança em Instalações e Serviços em Eletricidade',
    resumo: 'Requisitos para trabalhos em instalações elétricas: projeto, medidas de controle, desenergização, qualificação e autorização dos trabalhadores.',
    pontos: [
      'Só trabalham com eletricidade profissionais qualificados, habilitados ou capacitados e formalmente autorizados.',
      'Curso básico de 40h; complementar SEP de 40h para o Sistema Elétrico de Potência; reciclagem bienal e em caso de troca de função/empresa, afastamento superior a 3 meses ou mudanças significativas.',
      'Desenergização: seccionamento → impedimento de reenergização (bloqueio e etiquetagem) → constatação da ausência de tensão → aterramento temporário com equipotencialização → proteção dos elementos energizados na zona controlada → sinalização de impedimento.',
      'Prontuário das Instalações Elétricas obrigatório para carga instalada acima de 75 kW.',
      'Faixas: extrabaixa tensão até 50 V CA/120 V CC; baixa tensão até 1000 V CA/1500 V CC; acima disso, alta tensão.',
    ],
    documentos: ['Prontuário das instalações elétricas', 'Diagramas unifilares', 'Procedimentos e autorizações', 'Certificados NR-10'],
    palavras: 'eletricidade eletrica choque arco eletrico desenergizacao bloqueio etiquetagem loto sep painel quadro alta tensao baixa tensao',
  },
  11: {
    titulo: 'Transporte, Movimentação, Armazenagem e Manuseio de Materiais',
    resumo: 'Regras para equipamentos de movimentação (empilhadeiras, pontes rolantes, talhas, esteiras) e para armazenagem de materiais.',
    pontos: [
      'Equipamentos devem indicar em local visível a carga máxima de trabalho permitida.',
      'Operadores de equipamentos motorizados devem ser habilitados e portar cartão de identificação com nome e fotografia; o cartão vale 1 ano e a revalidação exige exame de saúde completo.',
      'Equipamentos motorizados devem ter sinal de advertência sonora (buzina).',
      'Em locais fechados, a emissão de gases de motores a combustão deve ser controlada.',
      'Materiais armazenados sem obstruir portas, equipamentos de incêndio e saídas de emergência.',
    ],
    palavras: 'empilhadeira movimentacao carga armazenagem ponte rolante talha esteira transpaleteira cartao operador',
  },
  12: {
    titulo: 'Segurança no Trabalho em Máquinas e Equipamentos',
    resumo: 'Princípios e medidas de proteção para garantir a segurança em todas as fases de uso de máquinas: projeto, instalação, operação, manutenção e descarte.',
    pontos: [
      'Zonas de perigo protegidas por proteções fixas, móveis com intertravamento ou dispositivos de segurança (cortinas de luz, comandos bimanuais etc.).',
      'Dispositivos de parada de emergência acessíveis e que não possam ser rearmados sem intenção.',
      'Manutenção, limpeza e ajustes com a máquina parada e com bloqueio das fontes de energia (energia zero).',
      'Operadores capacitados e máquinas com manual e sinalização em língua portuguesa.',
      'Apreciação de riscos segundo normas técnicas (ex.: ABNT NBR ISO 12100). Anexos tratam de prensas, injetoras, motosserras e outros.',
    ],
    palavras: 'maquina equipamento prensa protecao intertravamento parada de emergencia bloqueio motosserra injetora serra torno',
  },
  13: {
    titulo: 'Caldeiras, Vasos de Pressão, Tubulações e Tanques Metálicos de Armazenamento',
    resumo: 'Requisitos de instalação, inspeção, operação e manutenção de caldeiras, vasos de pressão, tubulações e tanques.',
    pontos: [
      'Profissional Habilitado (PH) responsável por inspeções e projetos.',
      'Prontuário, registro de segurança e relatórios de inspeção (inicial, periódica e extraordinária).',
      'Operador de caldeira com treinamento de segurança na operação e estágio prático.',
      'Válvulas de segurança, instrumentos de pressão e placa de identificação obrigatórios.',
    ],
    palavras: 'caldeira vaso de pressao tubulacao tanque vapor valvula de seguranca inspecao ph',
  },
  14: { titulo: 'Fornos', resumo: 'Fornos devem ter construção sólida, revestimento refratário e instalação que evite acúmulo de gases e exposição a altas temperaturas.', pontos: ['Proteção contra queimaduras e contra vazamento de gases.', 'Escadas e plataformas de acesso seguras.'], palavras: 'forno calor refratario gases' },
  15: {
    titulo: 'Atividades e Operações Insalubres',
    resumo: 'Define limites de tolerância e as atividades insalubres, que dão direito ao adicional de insalubridade.',
    pontos: [
      'Adicional de 40% (grau máximo), 20% (médio) ou 10% (mínimo), conforme a NR-15 (há discussão judicial sobre a base de cálculo).',
      'Ruído contínuo (Anexo 1): 85 dB(A) para 8h; a cada 5 dB a mais, o tempo permitido cai pela metade (ex.: 90 dB(A) → 4h; 95 dB(A) → 2h; 100 dB(A) → 1h).',
      'Outros anexos: ruído de impacto, calor, radiações, vibrações, frio, umidade, agentes químicos, poeiras minerais e agentes biológicos.',
      'A eliminação ou neutralização da insalubridade cessa o adicional (medidas coletivas ou EPI eficaz).',
    ],
    palavras: 'insalubridade insalubre adicional limite de tolerancia ruido calor poeira agente quimico biologico',
  },
  16: {
    titulo: 'Atividades e Operações Perigosas',
    resumo: 'Define as atividades perigosas, que dão direito ao adicional de periculosidade de 30% sobre o salário-base.',
    pontos: ['Explosivos, inflamáveis, energia elétrica, segurança pessoal/patrimonial com exposição a violência, motocicleta e radiações ionizantes.', 'O adicional não é acumulável com o de insalubridade (o trabalhador escolhe o mais vantajoso).'],
    palavras: 'periculosidade perigoso adicional 30 inflamavel explosivo eletricidade vigilante motociclista',
  },
  17: {
    titulo: 'Ergonomia',
    resumo: 'Parâmetros para adaptar as condições de trabalho às características dos trabalhadores, com foco em conforto, segurança e desempenho.',
    pontos: [
      'Avaliação Ergonômica Preliminar (AEP) das situações de trabalho e Análise Ergonômica do Trabalho (AET) quando necessário.',
      'Levantamento, transporte e descarga de materiais; mobiliário; equipamentos; condições ambientais; organização do trabalho.',
      'Anexos específicos para checkout e teleatendimento/telemarketing.',
    ],
    palavras: 'ergonomia postura aep aet mobiliario cadeira levantamento de peso ler dort pausa organizacao do trabalho',
  },
  18: {
    titulo: 'Segurança e Saúde no Trabalho na Indústria da Construção',
    resumo: 'Diretrizes de SST em obras de construção: PGR da obra, áreas de vivência, escavações, proteção contra quedas, andaimes, movimentação de cargas, instalações elétricas.',
    pontos: [
      'PGR da construção elaborado por profissional legalmente habilitado em SST.',
      'Proteção de periferia com guarda-corpo (travessão superior a 1,20 m, intermediário a 0,70 m e rodapé de 0,20 m) ou outra solução coletiva.',
      'Escavações com mais de 1,25 m exigem garantia de estabilidade dos taludes (escoramento/taludamento).',
      'Andaimes, plataformas, escadas e rampas conforme requisitos da norma; treinamento admissional e periódico.',
    ],
    palavras: 'construcao obra andaime escavacao vala periferia guarda-corpo canteiro concretagem demolicao',
  },
  19: { titulo: 'Explosivos', resumo: 'Requisitos para fabricação, manuseio, armazenamento e transporte de explosivos.', pontos: ['Depósitos com distâncias de segurança e controle de acesso.', 'Observância da regulamentação do Exército (produtos controlados).'], palavras: 'explosivo detonacao paiol polvora' },
  20: {
    titulo: 'Segurança e Saúde no Trabalho com Inflamáveis e Combustíveis',
    resumo: 'Requisitos para extração, produção, armazenamento, transferência, manuseio e manipulação de inflamáveis e líquidos combustíveis.',
    pontos: [
      'Instalações classificadas (classes I, II e III) conforme atividade e capacidade.',
      'Capacitação por tipo de atividade/instalação: integração, básico, intermediário, avançado I e II e específico.',
      'Prontuário da instalação, análise de riscos, controle de fontes de ignição e plano de resposta a emergências.',
      'Intervenções (manutenção, trabalho a quente) com permissão de trabalho.',
    ],
    palavras: 'inflamavel combustivel gasolina diesel etanol glp tanque abastecimento posto',
  },
  21: { titulo: 'Trabalhos a Céu Aberto', resumo: 'Exige proteção dos trabalhadores contra intempéries: abrigos, medidas contra insolação, calor, frio, umidade e ventos.', pontos: ['Abrigos para proteção contra intempéries.', 'Água potável e medidas contra insolação.'], palavras: 'ceu aberto sol calor chuva intemperie abrigo' },
  22: { titulo: 'Segurança e Saúde Ocupacional na Mineração', resumo: 'Requisitos específicos para atividades de mineração, com PGR próprio, CIPAMIN e controles de subsolo, explosivos, ventilação e estabilidade.', pontos: ['Programa de gerenciamento de riscos específico da mineração.'], palavras: 'mineracao mina subsolo cipamin' },
  23: {
    titulo: 'Proteção Contra Incêndios',
    resumo: 'Obriga medidas de prevenção e combate a incêndio, saídas de emergência e informação/treinamento dos trabalhadores, conforme a legislação estadual e normas técnicas.',
    pontos: [
      'Saídas suficientes, sinalizadas e desobstruídas para rápida evacuação.',
      'Equipamentos de combate a incêndio conforme o Corpo de Bombeiros do estado (instruções técnicas).',
      'Informar os trabalhadores sobre uso de equipamentos, evacuação e alarmes.',
      'Classes de fogo: A (sólidos), B (líquidos/gases inflamáveis), C (equipamentos energizados), D (metais pirofóricos), K (óleos e gorduras de cozinha).',
    ],
    palavras: 'incendio extintor brigada rota de fuga saida de emergencia alarme hidrante evacuacao classe de fogo',
  },
  24: {
    titulo: 'Condições Sanitárias e de Conforto nos Locais de Trabalho',
    resumo: 'Requisitos de instalações sanitárias, vestiários, refeitórios, cozinhas, alojamentos e água potável.',
    pontos: ['Instalações sanitárias separadas por sexo, na proporção de uma para cada 20 trabalhadores ou fração.', 'Água potável em condições higiênicas.', 'Vestiários quando houver troca de roupa ou exigência de higienização.'],
    palavras: 'sanitario banheiro vestiario refeitorio agua potavel alojamento conforto',
  },
  25: { titulo: 'Resíduos Industriais', resumo: 'Gerenciamento de resíduos sólidos, líquidos e gasosos de forma a proteger a saúde dos trabalhadores e o meio ambiente.', pontos: ['Resíduos identificados, segregados, acondicionados e destinados adequadamente.'], palavras: 'residuo lixo industrial descarte' },
  26: {
    titulo: 'Sinalização e Identificação de Segurança',
    resumo: 'Cores e sinalização de segurança em ambientes de trabalho e classificação/rotulagem de produtos químicos (GHS).',
    pontos: [
      'Cores para identificar equipamentos de segurança, delimitar áreas e identificar tubulações, conforme normas técnicas oficiais.',
      'Produtos químicos classificados e rotulados pelo GHS (ABNT NBR 14725), com Ficha com Dados de Segurança (FDS) disponível.',
      'A sinalização complementa — não substitui — as medidas de prevenção.',
    ],
    palavras: 'sinalizacao cor placa faixa demarcacao ghs rotulagem fds fispq sinalizacao vertical sinalizacao horizontal',
  },
  28: { titulo: 'Fiscalização e Penalidades', resumo: 'Procedimentos de fiscalização e gradação das multas por descumprimento das NRs.', pontos: ['Multas graduadas conforme a infração e o porte da empresa.'], palavras: 'fiscalizacao multa penalidade auto de infracao' },
  29: { titulo: 'Segurança e Saúde no Trabalho Portuário', resumo: 'Requisitos para operações portuárias, a bordo e em terra.', pontos: ['Plano de controle de emergência e requisitos de movimentação de cargas.'], palavras: 'porto portuario estiva' },
  30: { titulo: 'Segurança e Saúde no Trabalho Aquaviário', resumo: 'Requisitos para trabalhadores em embarcações comerciais.', pontos: [], palavras: 'aquaviario embarcacao navio' },
  31: { titulo: 'Segurança e Saúde no Trabalho na Agricultura, Pecuária, Silvicultura, Exploração Florestal e Aquicultura', resumo: 'Requisitos de SST no meio rural, com PGRTR, uso de agrotóxicos, máquinas agrícolas e condições de vivência.', pontos: ['PGRTR — Programa de Gerenciamento de Riscos no Trabalho Rural.', 'Regras para aplicação e armazenamento de agrotóxicos.'], palavras: 'rural agricultura agrotoxico trator pecuaria' },
  32: {
    titulo: 'Segurança e Saúde no Trabalho em Serviços de Saúde',
    resumo: 'Proteção de trabalhadores de serviços de saúde contra riscos biológicos, químicos e radiações.',
    pontos: ['Vedado reencapar e desconectar agulhas manualmente.', 'Vacinação gratuita (tétano, difteria, hepatite B e as previstas no PCMSO).', 'Vedado uso de adornos, calçados abertos e consumo de alimentos nos postos com risco biológico.'],
    palavras: 'saude hospital clinica perfurocortante agulha biologico vacina enfermagem',
  },
  33: {
    titulo: 'Segurança e Saúde nos Trabalhos em Espaços Confinados',
    resumo: 'Requisitos para identificar espaços confinados e controlar os riscos da entrada e do trabalho neles.',
    pontos: [
      'Espaço confinado: não projetado para ocupação humana contínua, com meios limitados de entrada e saída e onde exista ou possa existir atmosfera perigosa.',
      'Entrada somente com PET (Permissão de Entrada e Trabalho), vigia permanente e supervisor de entrada.',
      'Monitoramento da atmosfera antes e durante o trabalho (O₂ entre 19,5% e 23%, inflamáveis abaixo de 10% do LIE, tóxicos abaixo dos limites).',
      'Capacitação: 16h para trabalhadores autorizados e vigias; 40h para supervisores de entrada; reciclagem periódica anual.',
      'Equipe de resgate e procedimentos de emergência definidos; proibido trabalho individual.',
    ],
    documentos: ['PET', 'Cadastro dos espaços confinados', 'Certificados NR-33', 'Registros de monitoramento'],
    palavras: 'espaco confinado pet vigia supervisor de entrada tanque silo galeria atmosfera oxigenio lie',
  },
  34: { titulo: 'Condições e Meio Ambiente de Trabalho na Indústria da Construção, Reparação e Desmonte Naval', resumo: 'Requisitos para estaleiros: trabalho a quente, pintura, jateamento, movimentação de cargas e espaços confinados.', pontos: [], palavras: 'naval estaleiro navio' },
  35: {
    titulo: 'Trabalho em Altura',
    resumo: 'Requisitos para todo trabalho acima de 2,00 m do nível inferior onde haja risco de queda: planejamento, organização, execução, treinamento e resgate.',
    pontos: [
      'Trabalho em altura: atividade executada acima de 2,00 m do nível inferior, onde haja risco de queda.',
      'Treinamento inicial teórico e prático de no mínimo 8h; reciclagem bienal de 8h; eventual em mudança de procedimento, após evento relevante, retorno de afastamento superior a 90 dias ou mudança de empresa.',
      'Trabalhador formalmente autorizado e com aptidão para trabalho em altura registrada no ASO.',
      'Análise de Risco para todo trabalho em altura; Permissão de Trabalho para atividades não rotineiras.',
      'Sistema de proteção contra quedas: preferência à proteção coletiva; proteção individual (cinto paraquedista, talabarte, trava-quedas) com ancoragem adequada.',
      'Plano de emergência e resgate com recursos disponíveis.',
    ],
    documentos: ['Análise de Risco (AR)', 'Permissão de Trabalho (PT)', 'Certificados NR-35', 'Autorização formal', 'ASO com aptidão'],
    palavras: 'altura queda cinto paraquedista talabarte trava-quedas ancoragem linha de vida andaime telhado escada resgate',
  },
  36: { titulo: 'Segurança e Saúde no Trabalho em Empresas de Abate e Processamento de Carnes e Derivados', resumo: 'Requisitos para frigoríficos: pausas psicofisiológicas, ergonomia, frio, facas e agentes biológicos.', pontos: ['Pausas psicofisiológicas distribuídas na jornada.', 'Controle do frio e da umidade.'], palavras: 'frigorifico abate carne camara fria' },
  37: { titulo: 'Segurança e Saúde em Plataformas de Petróleo', resumo: 'Requisitos de SST para plataformas de petróleo em águas jurisdicionais brasileiras.', pontos: [], palavras: 'plataforma petroleo offshore' },
  38: { titulo: 'Segurança e Saúde no Trabalho nas Atividades de Limpeza Urbana e Manejo de Resíduos Sólidos', resumo: 'Requisitos para coleta, varrição, triagem e destinação de resíduos sólidos urbanos.', pontos: ['Controle de riscos de atropelamento, biológicos e ergonômicos na coleta.'], palavras: 'limpeza urbana coleta de lixo gari residuo solido' },
};
NRS[2] = { titulo: 'Inspeção Prévia (revogada)', resumo: 'A NR-02 foi revogada em 2019.', pontos: [], palavras: 'inspecao previa revogada', revogada: true };
NRS[27] = { titulo: 'Registro Profissional do Técnico de Segurança (revogada)', resumo: 'A NR-27 foi revogada em 2008.', pontos: [], palavras: 'registro tecnico revogada', revogada: true };

// Tabela de ruído da NR-15 (Anexo 1): nível dB(A) → minutos permitidos por dia
const NR15_RUIDO = [[85, 480], [86, 420], [87, 360], [88, 300], [89, 270], [90, 240], [91, 210], [92, 180], [93, 160], [94, 135], [95, 120], [96, 105], [98, 75], [100, 60], [102, 45], [104, 35], [105, 30], [106, 25], [108, 20], [110, 15], [112, 10], [114, 8], [115, 7]];

// ---- Glossário ------------------------------------------------------------------
const GLOSSARY = [
  ['sinalização vertical', 'placas de sinalização,sinalizacao por placas', 'São as placas de segurança fixadas em paredes, colunas, postes ou suportes (proibição, obrigação, alerta, emergência e orientação). No trânsito interno, incluem placas de velocidade máxima, "PARE", área de empilhadeiras etc. Complementa a sinalização horizontal (marcações no piso).', [26, 23], 'Posicione na altura da visão, com boa iluminação, e use pictogramas padronizados (ABNT NBR 13434 para emergência e ISO 7010).'],
  ['sinalização horizontal', 'demarcacao de piso,faixa de piso,faixas amarelas', 'São as marcações pintadas ou adesivadas no piso: faixas de circulação de pedestres e veículos, áreas de armazenagem, zebrados de áreas de risco, setas e áreas livres na frente de extintores e painéis.', [26, 11], 'Faixas de circulação bem conservadas reduzem atropelamentos por empilhadeiras.'],
  ['APR', 'analise preliminar de risco,analise preliminar de riscos', 'Análise Preliminar de Risco: documento que identifica, antes da atividade, as etapas, os perigos, os riscos, sua classificação e as medidas de controle, com a participação de quem executa.', [1], 'Faça a APR com a equipe, no local, e revise se as condições mudarem.'],
  ['AR', 'analise de risco', 'Análise de Risco: avaliação dos riscos de uma atividade específica. Na NR-35 é exigida para todo trabalho em altura.', [35, 1], ''],
  ['PT', 'permissao de trabalho', 'Permissão de Trabalho: autorização escrita, emitida para atividades não rotineiras ou de alto risco (altura, quente, eletricidade), com as medidas que devem estar implementadas antes do início, validade e responsáveis.', [35, 10, 20], 'A PT vale para aquela atividade, local e turno — encerre-a formalmente ao final.'],
  ['PET', 'permissao de entrada e trabalho', 'Permissão de Entrada e Trabalho: documento exigido pela NR-33 para entrada em espaço confinado, com medições da atmosfera, bloqueios, equipe, vigia e resgate.', [33], ''],
  ['DDS', 'dialogo diario de seguranca,dialogo de seguranca', 'Diálogo Diário de Segurança: conversa rápida (5 a 15 minutos) antes do início da jornada para tratar de riscos, lições aprendidas e comportamentos seguros.', [1], 'Um bom DDS é curto, prático, faz perguntas ao grupo e termina com um compromisso.'],
  ['EPI', 'equipamento de protecao individual', 'Equipamento de Proteção Individual: dispositivo de uso individual destinado a proteger contra riscos à segurança e saúde. Deve ter CA válido e é a última barreira na hierarquia de controles.', [6], ''],
  ['EPC', 'equipamento de protecao coletiva', 'Equipamento de Proteção Coletiva: protege todos os trabalhadores expostos — guarda-corpos, redes, enclausuramento de ruído, exaustão, proteções de máquinas, sinalização.', [1, 12, 18], 'Sempre priorize EPC antes do EPI.'],
  ['CA', 'certificado de aprovacao', 'Certificado de Aprovação: número emitido pelo Ministério do Trabalho que autoriza a comercialização e o uso de um EPI. Deve estar válido e gravado no equipamento.', [6], 'Consulte a validade do CA no sistema oficial (CAEPI) antes de comprar.'],
  ['ASO', 'atestado de saude ocupacional', 'Atestado de Saúde Ocupacional: documento emitido pelo médico após cada exame ocupacional (admissional, periódico, retorno, mudança de risco e demissional), com a conclusão de aptidão.', [7], ''],
  ['PCMSO', 'programa de controle medico de saude ocupacional', 'Programa de Controle Médico de Saúde Ocupacional: planeja os exames médicos conforme os riscos do PGR e acompanha a saúde dos trabalhadores.', [7], ''],
  ['PGR', 'programa de gerenciamento de riscos', 'Programa de Gerenciamento de Riscos: documento do GRO com o inventário de riscos e o plano de ação de cada estabelecimento.', [1], ''],
  ['GRO', 'gerenciamento de riscos ocupacionais', 'Gerenciamento de Riscos Ocupacionais: processo contínuo de identificar perigos, avaliar riscos, implementar e acompanhar medidas de prevenção (NR-01).', [1], ''],
  ['LTCAT', 'laudo tecnico das condicoes ambientais do trabalho', 'Laudo Técnico das Condições Ambientais do Trabalho: documento previdenciário que caracteriza a exposição a agentes nocivos para fins de aposentadoria especial.', [], ''],
  ['PPP', 'perfil profissiografico previdenciario', 'Perfil Profissiográfico Previdenciário: histórico laboral do trabalhador com as exposições a agentes nocivos; hoje é emitido eletronicamente via eSocial.', [], ''],
  ['CAT', 'comunicacao de acidente de trabalho', 'Comunicação de Acidente de Trabalho: deve ser emitida até o primeiro dia útil seguinte ao acidente e, em caso de morte, imediatamente (Lei 8.213/91, art. 22). No eSocial, evento S-2210.', [], 'Mesmo sem afastamento, o acidente de trabalho deve ser comunicado.'],
  ['acidente de trabalho', 'acidente do trabalho', 'É o que ocorre pelo exercício do trabalho a serviço da empresa, provocando lesão corporal ou perturbação funcional que cause morte, perda ou redução da capacidade para o trabalho (Lei 8.213/91, art. 19). Doenças ocupacionais e acidentes de trajeto são equiparados em certas condições.', [], ''],
  ['quase acidente', 'near miss,quase-acidente,incidente sem lesao', 'Evento que poderia ter causado lesão ou dano, mas não causou por acaso ou pouca margem. Registrar quase acidentes é uma das formas mais eficientes de prevenir acidentes graves.', [], 'Facilite o reporte (QR code, caixa, app) e dê retorno rápido a quem reportou.'],
  ['incidente', '', 'Ocorrência relacionada ao trabalho que resultou ou poderia ter resultado em lesão, doença ou dano. Inclui acidentes e quase acidentes.', [], ''],
  ['CIPA', 'comissao interna de prevencao de acidentes', 'Comissão Interna de Prevenção de Acidentes e de Assédio: formada por representantes do empregador e dos empregados para prevenir acidentes, doenças e assédio.', [5], ''],
  ['SESMT', 'servicos especializados em seguranca e medicina do trabalho', 'Serviços Especializados em Segurança e em Medicina do Trabalho: equipe de profissionais de SST dimensionada pela NR-04.', [4], ''],
  ['SIPAT', 'semana interna de prevencao de acidentes', 'Semana Interna de Prevenção de Acidentes do Trabalho: evento anual de conscientização organizado pela CIPA com o SESMT.', [5], 'Varie os formatos: gincanas, teatro, simulados e depoimentos engajam mais que palestras longas.'],
  ['LOTO', 'bloqueio e etiquetagem,lockout tagout,lockout', 'Lockout/Tagout — bloqueio e etiquetagem: procedimento para isolar e travar todas as fontes de energia (elétrica, hidráulica, pneumática, mecânica, térmica) com cadeados e etiquetas pessoais antes de manutenção ou limpeza.', [10, 12], 'Cada executante coloca o próprio cadeado; teste a energia zero antes de iniciar.'],
  ['FDS', 'fispq,ficha de informacoes de seguranca,ficha com dados de seguranca', 'Ficha com Dados de Segurança (antiga FISPQ): documento de 16 seções com perigos, composição, primeiros socorros, combate a incêndio, manuseio, EPIs e descarte de um produto químico (ABNT NBR 14725).', [26], 'A seção 8 indica os controles de exposição e EPIs.'],
  ['GHS', 'sistema globalmente harmonizado', 'Sistema Globalmente Harmonizado de classificação e rotulagem de produtos químicos, com pictogramas, palavras de advertência e frases de perigo.', [26], ''],
  ['LIE', 'limite inferior de explosividade,lel', 'Limite Inferior de Explosividade: menor concentração de um gás ou vapor no ar capaz de queimar/explodir. Em espaços confinados, a entrada exige inflamáveis abaixo de 10% do LIE.', [33, 20], ''],
  ['IPVS', 'imediatamente perigoso a vida ou a saude', 'Atmosfera Imediatamente Perigosa à Vida ou à Saúde: exige proteção respiratória de adução de ar (máscara autônoma ou linha de ar).', [33], ''],
  ['HHT', 'homem hora trabalhada,horas homem trabalhadas', 'Horas-homem de exposição ao risco: soma das horas trabalhadas por todos os empregados no período; base das taxas de frequência e gravidade (NBR 14280).', [], ''],
  ['taxa de frequência', 'tf,taxa de frequencia de acidentes', 'Taxa de Frequência (NBR 14280) = nº de acidentes × 1.000.000 ÷ HHT. Indica quantos acidentes ocorrem a cada milhão de horas trabalhadas.', [], 'Peça: "calcule a taxa de frequência com 3 acidentes e 450.000 HHT".'],
  ['taxa de gravidade', 'tg', 'Taxa de Gravidade (NBR 14280) = (dias perdidos + dias debitados) × 1.000.000 ÷ HHT.', [], ''],
  ['hierarquia de controles', 'hierarquia das medidas de controle', 'Ordem de prioridade das medidas de prevenção: eliminação → substituição → controles de engenharia/proteção coletiva → medidas administrativas → EPI.', [1], ''],
  ['SPIQ', 'sistema de protecao individual contra quedas', 'Sistema de Proteção Individual contra Quedas: conjunto de ancoragem, elemento de ligação (talabarte/trava-quedas) e cinturão paraquedista.', [35], ''],
  ['SPCQ', 'sistema de protecao coletiva contra quedas', 'Sistema de Proteção Coletiva contra Quedas: guarda-corpos, redes de proteção, fechamento de aberturas — preferencial ao SPIQ.', [35, 18], ''],
  ['talabarte', '', 'Elemento de ligação que conecta o cinturão paraquedista ao ponto de ancoragem. O talabarte duplo em Y permite ficar conectado 100% do tempo durante deslocamentos.', [35], ''],
  ['trava-quedas', 'trava quedas', 'Dispositivo que bloqueia automaticamente em caso de queda, deslizando em linha de vida (rígida/flexível) ou retrátil.', [35], ''],
  ['linha de vida', 'linha de ancoragem', 'Linha (cabo de aço, corda ou trilho) instalada entre ancoragens para permitir deslocamento conectado. Deve ser projetada por profissional legalmente habilitado.', [35], ''],
  ['ponto de ancoragem', 'ancoragem', 'Ponto destinado a suportar a carga de retenção de queda. Deve ser inspecionado e ter resistência dimensionada.', [35], ''],
  ['zona controlada', 'zona de risco', 'Na NR-10, zona controlada é o entorno de parte energizada restrito a trabalhadores autorizados; a zona de risco só pode ser acessada com técnicas e ferramentas apropriadas.', [10], ''],
  ['desenergização', 'desenergizacao', 'Sequência da NR-10 para considerar uma instalação desenergizada: seccionamento, impedimento de reenergização, constatação da ausência de tensão, aterramento temporário, proteção dos elementos energizados e sinalização.', [10], ''],
  ['arco elétrico', 'arco eletrico', 'Descarga elétrica através do ar que gera calor intenso, luz, pressão e projeção de metal fundido. A vestimenta deve ter ATPV compatível com a energia incidente calculada.', [10], ''],
  ['ATPV', 'arc thermal performance value', 'Valor de desempenho térmico ao arco (cal/cm²) de uma vestimenta antichama; deve ser maior que a energia incidente do local.', [10], ''],
  ['PFF2', 'respirador pff2,mascara pff2', 'Peça Facial Filtrante classe 2: respirador descartável para poeiras, névoas e fumos (e agentes biológicos). Precisa de boa vedação no rosto — barba compromete a proteção.', [6], 'Faça ensaio de vedação e troque quando sujo, danificado ou com dificuldade para respirar.'],
  ['PCA', 'programa de conservacao auditiva', 'Programa de Conservação Auditiva: conjunto de ações para prevenir a perda auditiva — avaliação do ruído, controles, EPI adequado, audiometrias e treinamento.', [7, 9], ''],
  ['PPR', 'programa de protecao respiratoria', 'Programa de Proteção Respiratória: seleção, uso, ensaio de vedação, manutenção e treinamento para respiradores (Fundacentro).', [6], ''],
  ['PAIR', 'perda auditiva induzida por ruido', 'Perda Auditiva Induzida por Ruído: perda gradual, irreversível e indolor causada por exposição prolongada a ruído elevado.', [7, 15], ''],
  ['dosimetria', 'dosimetro', 'Avaliação da exposição ao ruído ao longo da jornada com um dosímetro, resultando em dose (%) e nível equivalente.', [9, 15], ''],
  ['insalubridade', 'adicional de insalubridade', 'Condição de trabalho com exposição a agentes nocivos acima dos limites de tolerância (NR-15), que dá direito a adicional de 10%, 20% ou 40%.', [15], ''],
  ['periculosidade', 'adicional de periculosidade', 'Condição de risco acentuado (inflamáveis, explosivos, eletricidade, violência, motocicleta, radiações) que dá direito a adicional de 30% (NR-16).', [16], ''],
  ['AEP', 'avaliacao ergonomica preliminar', 'Avaliação Ergonômica Preliminar: avaliação inicial das situações de trabalho exigida pela NR-17, podendo ser qualitativa e simplificada.', [17], ''],
  ['AET', 'analise ergonomica do trabalho', 'Análise Ergonômica do Trabalho: análise aprofundada, exigida quando a AEP indica necessidade ou em situações previstas na NR-17.', [17], ''],
  ['5S', 'cinco s,housekeeping', 'Método de organização: Seiri (utilização), Seiton (ordenação), Seiso (limpeza), Seiketsu (padronização) e Shitsuke (disciplina). Organização e limpeza reduzem quedas, cortes e incêndios.', [], ''],
  ['5 porquês', '5 porques,cinco porques', 'Técnica de investigação que pergunta "por quê?" sucessivamente (em geral 5 vezes) até chegar à causa raiz de um problema ou acidente.', [], ''],
  ['Ishikawa', 'diagrama de ishikawa,espinha de peixe,6m', 'Diagrama de causa e efeito (espinha de peixe) que organiza as causas em categorias: Método, Mão de obra, Máquina, Material, Meio ambiente e Medida.', [], ''],
  ['5W2H', 'plano 5w2h', 'Ferramenta de plano de ação: What (o quê), Why (por quê), Where (onde), When (quando), Who (quem), How (como) e How much (quanto custa).', [], ''],
  ['POP', 'procedimento operacional padrao,instrucao de trabalho', 'Procedimento Operacional Padrão: descreve passo a passo como executar uma tarefa de forma segura e padronizada.', [], ''],
  ['ordem de serviço', 'os de seguranca,ordem de servico de seguranca', 'Documento que informa ao trabalhador os riscos da função, as medidas de prevenção, EPIs, obrigações e proibições (NR-01, item 1.4.1). Deve ter a ciência do empregado.', [1], ''],
  ['direito de recusa', 'recusa ao trabalho,interromper atividade', 'O trabalhador pode interromper suas atividades quando constatar situação de risco grave e iminente para sua vida ou saúde, informando imediatamente o superior (NR-01).', [1], ''],
  ['espaço confinado', 'espaco confinado', 'Ambiente não projetado para ocupação humana contínua, com meios limitados de entrada e saída e onde existe ou pode existir atmosfera perigosa (NR-33).', [33], ''],
  ['trabalho em altura', '', 'Toda atividade executada acima de 2,00 m do nível inferior, onde haja risco de queda (NR-35).', [35], ''],
  ['trabalho a quente', 'trabalho quente', 'Atividades que geram calor, chama ou faíscas (solda, corte, esmerilhamento) capazes de iniciar incêndio ou explosão. Exigem permissão de trabalho, afastamento de inflamáveis e vigia de fogo.', [20, 23], ''],
  ['brigada de incêndio', 'brigada de emergencia,brigadista', 'Grupo de trabalhadores treinados para prevenção, abandono de área, combate a princípios de incêndio e primeiros socorros, dimensionado conforme normas do Corpo de Bombeiros.', [23], ''],
  ['rota de fuga', 'saida de emergencia,rota de evacuacao', 'Caminho sinalizado e desobstruído até um local seguro (ponto de encontro) em caso de emergência.', [23, 26], ''],
  ['extintor', 'extintores,classes de extintor', 'Classes: A (sólidos — água, espuma, pó ABC), B (líquidos inflamáveis — espuma, CO₂, pó), C (equipamentos energizados — CO₂, pó BC/ABC), D (metais — pó especial), K (óleo de cozinha — agente classe K).', [23], 'Mantenha a área em frente ao extintor livre e sinalizada, com inspeção mensal visual.'],
  ['ato inseguro', 'condicao insegura', 'Termos antigos que classificavam causas de acidentes em comportamento (ato) ou ambiente (condição). Hoje se prefere analisar fatores organizacionais e falhas de barreiras, sem buscar culpados.', [], ''],
  ['riscos psicossociais', 'fatores psicossociais,saude mental,estresse,burnout', 'Fatores relacionados à organização do trabalho (sobrecarga, metas abusivas, assédio, falta de autonomia, conflitos) que podem causar adoecimento físico e mental. Devem ser considerados no GRO (NR-01).', [1, 17, 5], ''],
  ['eSocial SST', 'esocial,s-2210,s-2220,s-2240', 'Eventos de SST no eSocial: S-2210 (CAT), S-2220 (monitoramento da saúde — ASO) e S-2240 (condições ambientais — agentes nocivos).', [], ''],
  ['NBR 14280', 'nbr14280', 'Norma ABNT de cadastro de acidentes do trabalho: define critérios de registro e as taxas de frequência e gravidade.', [], ''],
  ['ISO 45001', 'iso45001', 'Norma internacional de sistemas de gestão de saúde e segurança ocupacional, baseada no ciclo PDCA e na participação dos trabalhadores.', [], ''],
];

// ---- Orientações práticas (situações do dia a dia) -------------------------------
const ADVICE = [
  {
    id: 'epi_recusa',
    gatilhos: /(nao (usa|usam|quer|querem|gosta|gostam)|recusa|se recusa|resiste|resistencia|esquece|tira|tiram|retira).{0,40}(epi|protetor|abafador|plug|capacete|oculos|luva|mascara|respirador|cinto|botina|bota)|(epi|protetor|abafador|capacete|oculos|luva|mascara|cinto).{0,30}(nao (usa|usam)|sem uso|recusa)/,
    titulo: 'Equipe que não usa o EPI',
    passos: [
      '**Entenda o porquê** antes de cobrar: converse com 2–3 pessoas. Os motivos mais comuns são desconforto (tamanho, calor, pressão), atrapalhar a comunicação, falta de hábito ou de exemplo da liderança.',
      '**Resolva a causa**: ofereça opções de modelo e tamanho (ex.: plug moldável × concha para protetor auricular), faça ajuste individual e teste de vedação quando aplicável.',
      '**Treine de forma prática**: mostre o risco real (para ruído, a PAIR é irreversível e indolor — a pessoa só percebe quando já perdeu audição) e como colocar corretamente.',
      '**Liderança dá o exemplo**: supervisores e visitantes usando o EPI na área, sempre.',
      '**Sinalize e padronize**: placas de uso obrigatório na entrada da área e ficha de entrega assinada (NR-06).',
      '**Acompanhe**: inspeções rápidas de uso, feedback positivo para quem usa e conversa individual com quem não usa.',
      '**Último recurso**: a recusa injustificada ao uso do EPI é ato faltoso (CLT art. 158) — aplique medidas disciplinares progressivas e documentadas.',
      '**E não esqueça a hierarquia de controles**: reduzir o risco na fonte (manutenção, enclausuramento, barreiras) diminui a dependência do EPI.',
    ],
    nrs: [6, 1],
    ofertas: [['DDS sobre o tema', 'Faz um DDS sobre uso de protetor auricular'], ['Ficha de entrega de EPI', 'Gera uma ficha de entrega de EPI'], ['Comunicado de uso obrigatório', 'Faz um comunicado de uso obrigatório de protetor auricular']],
  },
  {
    id: 'acidente_ocorreu',
    gatilhos: /(aconteceu|ocorreu|teve|tivemos|houve|sofreu|se machucou|machucou|caiu|cortou|quebrou|atropel).{0,40}(acidente|lesao|ferido|machucad|queda|corte|fratura)|acidente (hoje|agora|ontem|grave)/,
    titulo: 'Acidente aconteceu — primeiros passos',
    passos: [
      '**Socorro primeiro**: garanta a segurança da cena e acione o atendimento (SAMU 192 / Bombeiros 193). Não mova a vítima se houver suspeita de lesão na coluna.',
      '**Isole a área** e preserve o local e as evidências (fotos, equipamentos, documentos).',
      '**Comunique** a liderança, o SESMT/CIPA e o RH.',
      '**Emita a CAT** até o 1º dia útil seguinte (em caso de morte, imediatamente) — evento S-2210 no eSocial.',
      '**Investigue** com a equipe em até 24–72h: descreva o ocorrido, ouça testemunhas e use 5 porquês/Ishikawa para chegar às causas raiz (sem buscar culpados).',
      '**Plano de ação** (5W2H) com prazos e responsáveis, e **compartilhe as lições aprendidas** em DDS.',
    ],
    nrs: [1],
    ofertas: [['Relatório de investigação', 'Gera um relatório de investigação de acidente'], ['Plano de ação 5W2H', 'Monta um plano de ação 5W2H'], ['Alerta de segurança', 'Faz um alerta de segurança sobre o acidente']],
  },
  {
    id: 'quase_acidente',
    gatilhos: /(ninguem|pouca gente|equipe nao|nao) (reporta|relata|comunica|registra).{0,30}(quase|incidente|desvio)|aumentar (os )?(reportes|relatos)|cultura de seguranca/,
    titulo: 'Aumentar o reporte de quase acidentes',
    passos: [
      '**Facilite**: formulário de 1 minuto, QR code nas áreas, caixa física e reporte verbal ao líder.',
      '**Cultura justa**: deixe claro que reportar não gera punição — erros honestos viram aprendizado.',
      '**Dê retorno rápido**: todo reporte recebe resposta e, quando possível, uma ação visível.',
      '**Reconheça**: destaque os melhores reportes do mês no DDS.',
      '**Mostre o impacto**: indicadores simples (reportes × ações concluídas) no mural.',
    ],
    nrs: [1, 5],
    ofertas: [['Aba de registro de ocorrências', 'Crie uma aba para registrar quase acidentes com campos: data, setor, descrição, gravidade, status'], ['DDS sobre quase acidentes', 'Faz um DDS sobre a importância de reportar quase acidentes']],
  },
  {
    id: 'fiscalizacao',
    gatilhos: /(fiscalizacao|fiscal|auditoria|auditor|ministerio do trabalho|mte).{0,40}(vem|vai|chegando|semana|amanha|visita|preparar)|preparar (para|pra) (a )?(fiscalizacao|auditoria)/,
    titulo: 'Preparação para fiscalização/auditoria',
    passos: [
      '**PGR** atualizado (inventário de riscos + plano de ação) e **PCMSO** com relatório analítico.',
      '**ASOs** em dia de todos os empregados.',
      '**Treinamentos** obrigatórios com certificados válidos (NR-05, 06, 10, 11, 12, 33, 35 etc., conforme as atividades).',
      '**Fichas de entrega de EPI** assinadas, com CAs válidos.',
      '**CIPA/representante nomeado**: atas de eleição, posse e reuniões.',
      '**Ordens de serviço**, procedimentos, PTs/APRs arquivadas e inspeções registradas.',
      '**Prontuários** (elétrico NR-10, caldeiras NR-13) e laudos (LTCAT, insalubridade/periculosidade).',
      '**Eventos do eSocial SST** (S-2210, S-2220, S-2240) enviados.',
    ],
    nrs: [1, 7, 6, 5, 28],
    ofertas: [['Checklist documental', 'Faz um checklist de documentos para fiscalização'], ['Plano de ação', 'Monta um plano de ação 5W2H para a auditoria']],
  },
  {
    id: 'altura_sem_cinto',
    gatilhos: /(sem cinto|sem talabarte|nao (usa|usam|estava) (o )?cinto|desconectad|sem estar preso).{0,40}|(altura|telhado|andaime).{0,40}(sem cinto|sem protecao|sem epi)/,
    titulo: 'Trabalho em altura sem proteção',
    passos: [
      '**Pare a atividade imediatamente** — é risco grave e iminente (direito/dever de interrupção, NR-01).',
      'Verifique se há **PT e AR** emitidas e se o trabalhador é **treinado (NR-35), autorizado e apto no ASO**.',
      'Garanta **proteção coletiva** (guarda-corpo, fechamento de aberturas) ou **ancoragem adequada** para o cinto paraquedista com talabarte duplo.',
      'Retome somente com as barreiras implementadas e o **plano de resgate** disponível.',
      'Registre como desvio grave e trate a causa (pressa, falta de ancoragem, falta de EPI, supervisão).',
    ],
    nrs: [35, 1],
    ofertas: [['APR de trabalho em altura', 'Faz uma APR de trabalho em altura'], ['PT de trabalho em altura', 'Gera uma permissão de trabalho em altura']],
  },
  {
    id: 'calor',
    gatilhos: /(muito )?(calor|quente demais|temperatura alta|insolacao|desidrata)/,
    titulo: 'Calor excessivo no trabalho',
    passos: [
      '**Avalie a exposição** (IBUTG, conforme NR-15 Anexo 3 e NR-09) nas áreas e atividades críticas.',
      '**Hidratação**: água fresca próxima e incentivo a beber pouco e sempre.',
      '**Pausas e revezamento** em locais frescos; atividades pesadas nos horários mais amenos.',
      '**Aclimatação** gradual de novos trabalhadores e de quem volta de férias.',
      '**Controles**: ventilação, exaustão, barreiras de radiação térmica, roupas leves e protetor solar/chapéu a céu aberto (NR-21).',
      '**Treine** para reconhecer sinais de exaustão e insolação (tontura, náusea, câimbras, confusão).',
    ],
    nrs: [15, 9, 21],
    ofertas: [['DDS sobre calor', 'Faz um DDS sobre exposição ao calor']],
  },
  {
    id: 'empilhadeira_sem_habilitacao',
    gatilhos: /(sem (treinamento|curso|cartao|habilitacao)|nao (e|tem) (habilitado|treinado)).{0,40}(empilhadeira|operador)|(empilhadeira|operador).{0,40}(sem (treinamento|curso|cartao|habilitacao))/,
    titulo: 'Operador de empilhadeira sem capacitação',
    passos: [
      '**Retire da operação** até concluir a capacitação — chave sob controle da liderança.',
      'Providencie **treinamento de operador** e **cartão de identificação** com nome e foto (NR-11), válido por 1 ano com exame de saúde para revalidar.',
      'Implante **checklist pré-operacional** diário e **autorização formal** dos operadores.',
      'Revise rotas, sinalização horizontal e velocidade máxima na área.',
    ],
    nrs: [11],
    ofertas: [['Checklist de empilhadeira', 'Gera um checklist de empilhadeira'], ['APR de empilhadeira', 'Faz uma APR de empilhadeira']],
  },
  {
    id: 'engajamento',
    gatilhos: /(engajar|motivar|conscientizar|envolver).{0,40}(equipe|time|pessoal|colaboradores|trabalhadores)|(campanha|ideias?) (de|para|pra) (seguranca|sipat|dds)/,
    titulo: 'Engajar a equipe em segurança',
    passos: [
      '**DDS participativo**: perguntas, casos reais da própria área e rodízio de quem conduz.',
      '**Reconhecimento** de comportamentos seguros e de bons reportes — não só de "dias sem acidentes".',
      '**Liderança visível**: caminhadas de segurança com escuta ativa.',
      '**Gamificação**: desafios por equipe (5S, inspeções, quiz de NR) com metas simples.',
      '**Comunicação visual**: mural com indicadores, alertas e lições aprendidas.',
      '**Dê voz**: implemente sugestões dos trabalhadores e mostre o antes/depois.',
    ],
    nrs: [1, 5],
    ofertas: [['Aba de indicadores', 'Crie uma aba de indicadores de segurança'], ['DDS criativo', 'Faz um DDS sobre percepção de risco']],
  },
  {
    id: 'psicossocial',
    gatilhos: /(saude mental|burnout|estresse|estressad|ansiedade|assedio|pressao (demais|excessiva)|sobrecarga)/,
    titulo: 'Riscos psicossociais e saúde mental',
    passos: [
      '**Inclua no GRO/PGR** os fatores psicossociais (NR-01): sobrecarga, metas, conflitos, assédio, jornada, falta de autonomia.',
      '**Ouça as pessoas**: pesquisas anônimas, rodas de conversa e canais seguros de denúncia (a CIPA também atua contra assédio — NR-05).',
      '**Organização do trabalho**: pausas, distribuição justa de tarefas, clareza de papéis, metas realistas.',
      '**Lideranças preparadas** para acolher e encaminhar; divulgue apoio psicológico disponível (CVV 188).',
      '**Monitore** afastamentos, rotatividade e absenteísmo como sinais de alerta.',
    ],
    nrs: [1, 5, 17],
    ofertas: [['DDS sobre saúde mental', 'Faz um DDS sobre saúde mental no trabalho']],
  },
  {
    id: 'terceiros',
    gatilhos: /(terceirizad|prestador|empreiteira|contratada|terceiros).{0,40}(seguranca|controle|documento|integracao|gestao)/,
    titulo: 'Gestão de terceiros/contratadas',
    passos: [
      '**Exija documentação antes da mobilização**: PGR/APR da atividade, ASOs, treinamentos (NRs aplicáveis), fichas de EPI.',
      '**Integração de segurança** obrigatória com as regras do local.',
      '**PT e acompanhamento** nas atividades de risco, com responsável da contratante.',
      '**Inspeções e indicadores** da contratada (desvios, acidentes, HHT).',
      '**Contrato** com cláusulas de SST e consequências por descumprimento.',
    ],
    nrs: [1],
    ofertas: [['Checklist de contratadas', 'Faz um checklist de documentação de terceiros']],
  },
  {
    id: 'quimicos_sem_fds',
    gatilhos: /(sem (fds|fispq|rotulo|identificacao)|nao tem (fds|fispq)|produto (sem|nao identificado))/,
    titulo: 'Produtos químicos sem FDS ou rótulo',
    passos: [
      '**Segregue** o produto e não utilize até identificá-lo.',
      '**Solicite a FDS** ao fabricante/fornecedor (obrigatória) e mantenha acessível aos trabalhadores.',
      '**Rotule** conforme GHS (ABNT NBR 14725): pictogramas, palavra de advertência e frases de perigo — inclusive em recipientes de transferência.',
      '**Armazene por compatibilidade**, com contenção e ventilação.',
      '**Treine** sobre perigos, EPIs (seção 8 da FDS) e emergências (seções 4 a 6).',
    ],
    nrs: [26, 9],
    ofertas: [['APR de produtos químicos', 'Faz uma APR de manuseio de produtos químicos']],
  },
  {
    id: 'housekeeping',
    gatilhos: /(bagunca|desorganiz|sujeira|sujo|housekeeping|organizacao e limpeza|5s)/,
    titulo: 'Organização e limpeza (5S)',
    passos: [
      '**Comece pequeno**: uma área piloto com o time que trabalha nela.',
      '**Descarte** o que não é usado, **defina lugar** para cada coisa (demarcação de piso) e **limpe** inspecionando.',
      '**Padronize** com fotos do "como deve estar" e **audite** semanalmente com checklist simples.',
      '**Mostre o resultado**: antes/depois e ranking entre áreas.',
    ],
    nrs: [26, 23],
    ofertas: [['Checklist 5S', 'Gera um checklist de 5S'], ['Aba de auditorias 5S', 'Crie uma aba para controlar auditorias 5S com campos: data, área, nota, responsável']],
  },
];

// ---- Conversa (small talk) ------------------------------------------------------------
const SMALLTALK = {
  como_esta: [
    'Tudo ótimo — ou o mais perto disso que uma IA consegue 😄 E aí, como você tá?',
    'Por aqui tudo em ordem, com os EPIs digitais ajustados 😄 E você, como está?',
    'Funcionando a todo vapor (com válvula de segurança calibrada 😉). E você, tudo bem?',
  ],
  bem: ['Que bom! 😊 Me conta: em que posso te ajudar hoje?', 'Fico feliz! Bora deixar o dia mais seguro? Me diz o que precisa.', 'Show! Tô por aqui para o que precisar — documentos, dúvidas de NR, abas novas…'],
  mal: [
    'Poxa, sinto muito. Se quiser, me conta o que houve — às vezes ajuda organizar as ideias. E se for algo mais pesado, o CVV atende 24h pelo 188. 💙',
    'Que pena… respira fundo. Posso aliviar alguma tarefa pra você agora? Posso gerar documentos, checklists ou resumir arquivos.',
  ],
  obrigado: ['Por nada! Conte comigo. 🦺', 'Imagina! Segurança em primeiro lugar — e eu tô aqui pra isso.', 'Disponha! Se precisar de mais alguma coisa, é só chamar.'],
  tchau: ['Até mais! Bom trabalho e volte sempre em segurança. 👋', 'Tchau! Qualquer coisa, tô por aqui.', 'Até logo! Lembre-se: ninguém se machuca hoje. 💪'],
  elogio: ['Obrigada! 😊 Você também manda bem. Vamos seguir?', 'Assim eu fico sem graça 😄 Obrigada! O que mais posso fazer por você?'],
};
